### ISSUE TITLE
Class attribute is not working

### ISSUE THREAD

**Issue by Nkzq** [asadowski10/advanced-responsive-images#9]
Lorsqu'on passe une class dans l'array d'attribut du `get_the_post_thumbnail`, celle-ci n'est pas visible côté front.

```php
<?php echo get_the_post_thumbnail( 0, $img, array( 'data-location' => 'location', 'class' => 'entry__img', 'alt' => 'Img description' ) ); ?>
```

**Comment by asadowski10** [comment]
Corrigé ici : https://github.com/BeAPI/beapi-frontend-framework/commit/c5e18245abf90af33e3ec4f61dabece538ee8b33 :)
